Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2023
Var
n1, i: inteiro


Inicio

Escreva ("Digite um número que deseja:")
 leia(n1)

para i<-1 ate 100 faca
escreval(n1,"x", i ,"=", n1*i)
fimpara


Fimalgoritmo