Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2023
Var
   sexo:caractere

Inicio

   repita

      escreva ("Digite sexo correto [M/F]:")
      leia   (sexo)

      limpatela

   ate (sexo="M") ou (sexo="F")


   escreval ("Sexo: ",sexo)


Fimalgoritmo
